# Site settings
title: Threads
description: > # this means to ignore newlines until "baseurl:"
  Attempting to combine fashion and ethics
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
